In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/gdriv')
data_path = "/content/gdriv/My Drive/Colab Notebooks/data" 
dt = pd.read_csv(data_path + '/cars_part_quality.csv')
pred_dt = pd.read_csv(data_path + '/term_data.csv')

Mounted at /content/gdriv

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
pred_dt

             date_time   T1   T2   T3  ...  T15  observe1  observe2  quality
0      2017-04-16 8:05  255  256  257  ...  276    190.21      6.67      352
1      2017-04-16 9:05  206  264  251  ...  285    170.96      7.56      366
2     2017-04-16 10:05  192  254  238  ...  286    171.84      7.21      352
3     2017-04-16 11:05  256  236  217  ...  284    174.71      8.78      349
4     2017-04-16 12:05  226  225  192  ...  283    174.55      6.89      341
...                ...  ...  ...  ...  ...  ...       ...       ...      ...
9179  2018-05-03 19:05  257  258  266  ...  252    157.47      7.33      438
9180  2018-05-03 20:05  259  255  260  ...  247    157.17      7.87      452
9181  2018-05-03 21:05  260  254  263  ...  247    155.00      7.65      455
9182  2018-05-03 22:05  255  255  260  ...  248    153.89      8.90      455
9183  2018-05-03 23:05  254  257  256  ...  245    157.46      6.39      454

[9184 rows x 19 columns]

In [4]:
dt

             date_time   T1   T2   T3  ...  T15  observe1  observe2  quality
0      2015-01-04 0:05  277  326  273  ...  242    153.77      7.90      392
1      2015-01-04 1:05  277  253  272  ...  230    158.27      6.96      384
2      2015-01-04 2:05  262  218  260  ...  240    153.36      7.29      393
3      2015-01-04 3:05  243  238  252  ...  246    153.21      7.11      399
4      2015-01-04 4:05  236  238  245  ...  265    195.71      7.97      400
...                ...  ...  ...  ...  ...  ...       ...       ...      ...
19995  2017-04-16 3:05  324  248  259  ...  220    172.78      7.52      316
19996  2017-04-16 4:05  256  253  262  ...  215    190.62      6.77      309
19997  2017-04-16 5:05  258  268  255  ...  229    189.90      8.84      328
19998  2017-04-16 6:05  260  261  237  ...  245    192.41      6.19      335
19999  2017-04-16 7:05  255  261  251  ...  262    188.21      7.03      345

[20000 rows x 19 columns]

In [5]:
t_dt = pd.concat([dt, pred_dt])

In [6]:
t_dt

             date_time   T1   T2   T3  ...  T15  observe1  observe2  quality
0      2015-01-04 0:05  277  326  273  ...  242    153.77      7.90      392
1      2015-01-04 1:05  277  253  272  ...  230    158.27      6.96      384
2      2015-01-04 2:05  262  218  260  ...  240    153.36      7.29      393
3      2015-01-04 3:05  243  238  252  ...  246    153.21      7.11      399
4      2015-01-04 4:05  236  238  245  ...  265    195.71      7.97      400
...                ...  ...  ...  ...  ...  ...       ...       ...      ...
9179  2018-05-03 19:05  257  258  266  ...  252    157.47      7.33      438
9180  2018-05-03 20:05  259  255  260  ...  247    157.17      7.87      452
9181  2018-05-03 21:05  260  254  263  ...  247    155.00      7.65      455
9182  2018-05-03 22:05  255  255  260  ...  248    153.89      8.90      455
9183  2018-05-03 23:05  254  257  256  ...  245    157.46      6.39      454

[29184 rows x 19 columns]

In [7]:
t_dt = t_dt.sort_values(['quality']).reset_index(drop=True)
print(t_dt)
label = []
for i in range(len(t_dt)):
  if i < int(np.round(len(t_dt)*0.33)):
    label.append(0)
  elif i >= int(np.round(len(t_dt)*0.33)) and i< int(np.round(len(t_dt)*0.66)):
    label.append(1)
  else:
    label.append(2)

              date_time   T1   T2   T3  ...  T15  observe1  observe2  quality
0       2016-04-18 5:05  206  204  204  ...  206    158.84      7.54      221
1       2018-01-24 2:05  234  171  229  ...  237    198.12      6.50      226
2       2018-01-24 1:05  230  316  230  ...  232    149.98      8.46      228
3      2016-06-02 23:05  206  215  205  ...  191    165.98      7.59      229
4       2018-01-24 0:05  229  280  234  ...  245    148.38      6.32      232
...                 ...  ...  ...  ...  ...  ...       ...       ...      ...
29179  2015-02-17 23:05  309  311  303  ...  297    182.27      8.39      501
29180   2015-02-18 0:05  299  300  300  ...  299    183.53      5.69      501
29181   2017-03-12 9:05  286  284  293  ...  303    149.95      7.10      501
29182  2015-02-17 21:05  305  311  311  ...  298    182.08      7.46      503
29183   2015-02-18 1:05  293  282  290  ...  298    185.73      8.01      505

[29184 rows x 19 columns]

In [8]:
label= pd.DataFrame(label)
counts = label.value_counts()
print(counts)

2    9923
0    9631
1    9630
dtype: int64

In [9]:
x = t_dt.iloc[:,1:18]
col = x.columns
x

        T1   T2   T3   T4   T5   T6  ...  T12  T13  T14  T15  observe1  observe2
0      206  204  204  421  310  421  ...  305  220  210  206    158.84      7.54
1      234  171  229  284  331  319  ...  379  248  236  237    198.12      6.50
2      230  316  230  289  308  303  ...  370  251  234  232    149.98      8.46
3      206  215  205  305  299  288  ...  404  246  202  191    165.98      7.59
4      229  280  234  331  352  311  ...  395  225  241  245    148.38      6.32
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...       ...
29179  309  311  303  337  327  340  ...  386  297  290  297    182.27      8.39
29180  299  300  300  348  338  341  ...  390  300  292  299    183.53      5.69
29181  286  284  293  342  350  860  ...  322  298  294  303    149.95      7.10
29182  305  311  311  346  343  339  ...  384  296  297  298    182.08      7.46
29183  293  282  290  355  357  357  ...  370  293  296  298    185.73      8.01

[29184 rows x 17 columns]

In [10]:
import sklearn.preprocessing 
scaler = sklearn.preprocessing.MinMaxScaler()
x = scaler.fit_transform(x)

In [72]:
trainx = dt.iloc[:,1:18].to_numpy()
trainy, testy = train_test_split(label, train_size=len(dt))
testx = pred_dt.iloc[:,1:18].to_numpy()

In [73]:
print(len(trainx))
print(len(trainy))
print(len(testx))
print(len(testy))

20000
20000
9184
9184

In [74]:
trainx = scaler.fit_transform(trainx)
testx = scaler.fit_transform(testx)

In [75]:
trainy = trainy.to_numpy()
testy = testy.to_numpy()

In [76]:
from sklearn.ensemble import RandomForestClassifier

In [77]:
model = RandomForestClassifier(n_estimators = 100, 
                              criterion = 'entropy',
                              max_depth = 12,
                              min_samples_leaf = 20,
                              min_samples_split = 20,
                              random_state = 0,
                              n_jobs = -1)

In [78]:
model = RandomForestClassifier()

In [79]:
trainy.shape

(20000, 1)

In [89]:
trainy = trainy.reshape(-1)

In [90]:
trainy.shape

(20000,)

In [91]:
model = model.fit(trainx, trainy)

In [92]:
pred_test = model.predict(testx)

In [94]:
pred_test

array([1, 0, 0, ..., 0, 0, 0])

In [96]:
len(pred_test)

9184

In [112]:
result = pd.concat([pd.DataFrame(pred_dt), pd.DataFrame(pred_test)],axis = 1)

In [113]:
result

             date_time   T1   T2   T3   T4  ...  T15  observe1  observe2  quality  0
0      2017-04-16 8:05  255  256  257  339  ...  276    190.21      6.67      352  1
1      2017-04-16 9:05  206  264  251  347  ...  285    170.96      7.56      366  0
2     2017-04-16 10:05  192  254  238  368  ...  286    171.84      7.21      352  0
3     2017-04-16 11:05  256  236  217  350  ...  284    174.71      8.78      349  0
4     2017-04-16 12:05  226  225  192  342  ...  283    174.55      6.89      341  0
...                ...  ...  ...  ...  ...  ...  ...       ...       ...      ... ..
9179  2018-05-03 19:05  257  258  266  379  ...  252    157.47      7.33      438  0
9180  2018-05-03 20:05  259  255  260  372  ...  247    157.17      7.87      452  0
9181  2018-05-03 21:05  260  254  263  364  ...  247    155.00      7.65      455  0
9182  2018-05-03 22:05  255  255  260  356  ...  248    153.89      8.90      455  0
9183  2018-05-03 23:05  254  257  256  349  ...  245    157.46      6.39      454  0

[9184 rows x 20 columns]

In [127]:
result.rename(columns = {0 : "label"}, inplace = True)

In [128]:
print(result)

             date_time   T1   T2   T3  ...  observe1  observe2  quality  label
0      2017-04-16 8:05  255  256  257  ...    190.21      6.67      352      1
1      2017-04-16 9:05  206  264  251  ...    170.96      7.56      366      0
2     2017-04-16 10:05  192  254  238  ...    171.84      7.21      352      0
3     2017-04-16 11:05  256  236  217  ...    174.71      8.78      349      0
4     2017-04-16 12:05  226  225  192  ...    174.55      6.89      341      0
...                ...  ...  ...  ...  ...       ...       ...      ...    ...
9179  2018-05-03 19:05  257  258  266  ...    157.47      7.33      438      0
9180  2018-05-03 20:05  259  255  260  ...    157.17      7.87      452      0
9181  2018-05-03 21:05  260  254  263  ...    155.00      7.65      455      0
9182  2018-05-03 22:05  255  255  260  ...    153.89      8.90      455      0
9183  2018-05-03 23:05  254  257  256  ...    157.46      6.39      454      0

[9184 rows x 20 columns]

In [129]:
result

             date_time   T1   T2   T3  ...  observe1  observe2  quality  label
0      2017-04-16 8:05  255  256  257  ...    190.21      6.67      352      1
1      2017-04-16 9:05  206  264  251  ...    170.96      7.56      366      0
2     2017-04-16 10:05  192  254  238  ...    171.84      7.21      352      0
3     2017-04-16 11:05  256  236  217  ...    174.71      8.78      349      0
4     2017-04-16 12:05  226  225  192  ...    174.55      6.89      341      0
...                ...  ...  ...  ...  ...       ...       ...      ...    ...
9179  2018-05-03 19:05  257  258  266  ...    157.47      7.33      438      0
9180  2018-05-03 20:05  259  255  260  ...    157.17      7.87      452      0
9181  2018-05-03 21:05  260  254  263  ...    155.00      7.65      455      0
9182  2018-05-03 22:05  255  255  260  ...    153.89      8.90      455      0
9183  2018-05-03 23:05  254  257  256  ...    157.46      6.39      454      0

[9184 rows x 20 columns]